"""empty message

Revision ID: e70c28953e0a
Revises: 475068ae1757
Create Date: 2020-08-26 09:32:16.130108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70c28953e0a'
down_revision = '475068ae1757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
