"""empty message

Revision ID: fbe143775742
Revises: 563a72309237
Create Date: 2020-08-28 09:43:36.886451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe143775742'
down_revision = '563a72309237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumb',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'bid')
    )
    op.add_column('blog', sa.Column('n_thumb', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'n_thumb')
    op.drop_table('thumb')
    # ### end Alembic commands ###
